name: Musicgen Image

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - run: df -h
      - run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo service docker stop
          echo "Docker Stopped"
          sudo mv /var/lib/docker /mnt/docker-data
          echo "Docker data moved"
          sudo ln -s /mnt/docker-data /var/lib/docker
          echo "Docker data relinked"
          sudo service docker start
          echo "Docker Restarted"
          df -h
      - name: Build and push image
        env:
          CONTEXT: ./builder/musicgen
          IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:musicgen-1.1
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_REGISTRY }}
          docker buildx build --platform=linux/amd64 -t $IMAGE --push $CONTEXT
