name: Stable Diffusion XL Docker Image

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build and push image
        env:
          CONTEXT: ./builder/stable-diffusion-xl
          SDXL_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:stable-diffusion-xl-1.0
          ANIMAGINE_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}/animagine-xl-1.0
        run: |
          export DOCKER_BUILDKIT=1
          export PROGRESS_NO_TRUNC=1
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_REGISTRY }}
          docker buildx build --platform=linux/amd64 -t $SDXL_IMAGE --target sdxl --push $CONTEXT
          docker buildx prune --force
          docker buildx build --platform=linux/amd64 -t $ANIMAGINE_IMAGE --target animagine --push $CONTEXT
