name: Stable Diffusion XL Docker Image

# configure manual trigger
on:
  workflow_dispatch:

jobs:
  sdxl:
    runs-on: ubuntu-22.04
    steps:
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Build and push image
        env:
          CONTEXT: ./builder/stable-diffusion-xl
          SDXL_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:sd-xl-1.1
          ANIMAGINE_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:animagine-xl-1.1
          REALVIS_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:realvis-xl-1.1
          AAM_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:aam-xl-1.1
          PONY_IMAGE: ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKERHUB_NAMESPACE }}:pony-xl-1.1
        run: |
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_PASSWORD }} ${{ secrets.DOCKERHUB_REGISTRY }}
          docker build -t $SDXL_IMAGE --target sdxl --push $CONTEXT
          docker build -t $ANIMAGINE_IMAGE --target animagine --push $CONTEXT
          docker build -t $REALVIS_IMAGE --target realvisxl --push $CONTEXT
          docker build -t $AAM_IMAGE --target aamxl --push $CONTEXT
          docker build -t $PONY_IMAGE --target ponyxl --push $CONTEXT
